### ISSUE TITLE
[BUG] Named dragon looses name when summoned

### ISSUE THREAD

**Issue by labkeeper** [Wyrmheart-Team/Dragon_Mounts_Remastered#14] opened 2024-12-19 20:38 UTC
**Describe the bug**
When you name your dragon with the name tag, name persists only until first dragon re-spawn, like by waypoint travel or summon by whistle

**To Reproduce**
Edit name tag and put it on your dragon. Move away about 64 blocks and use whistle. Name is gone.

**Expected behavior**
Dragon name should be set in NBT and restored after spawning dragon.

**Screenshots**

**Additional context**

**Comment by Horeak** [comment] 2024-12-20 06:45
Are you playing with any other mods that could affect it? As i am having trouble trying to reproduce this bug as it is working as intended on my side.

**Comment by Horeak** [comment] 2024-12-25 03:21
Closing this issue until more info is given, since as of latest version (1.5.3 at the time of writing) i am unable to reproduce this issue.

**Closed by Horeak** 2024-12-25 03:21 UTC
Labels: bug, need info
